### ISSUE TITLE
domready "interactive" state needs IE workaround

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/shoestring#33]
Shoestring’s domready allows it to run when the readystate is "interactive," which is good because otherwise domcontentloaded can be delayed later than we want, waiting for onload-type scheduling like image requests. We need a way to avoid allowing the `interactive` ready state if the browser is IE. This workaround looks good https://github.com/mobify/mobifyjs/pull/177/files

We should consider how to handle that here: https://github.com/filamentgroup/shoestring/blob/master/src/shoestring.js#L198

**Comment by zachleat** [comment]
Closing per @scottjehl’s slack signoff https://filamentgroup.slack.com/archives/shoestring/p1487100168000107

The mobify workaround above has been included in the codebase too.
