### ISSUE TITLE
Dist files not being generated when I do a bower install.

### ISSUE THREAD

**Issue by jonathanconway** [filamentgroup/shoestring#90]
Today I installed shoestring via Bower, using the following:

`bower install shoestring --save`

When I navigated to the dist folder under bower_components\shoestring, it was empty.

Can we have dist files generated at the same time as the bower install happens?

I would expect this to happen, as this is what happens when I do an `npm install`.

**Comment by zachleat** [comment]
Sorry for the late response (and the unsatisfactory response), but we do not support bower for shoestring.
