### ISSUE TITLE
require("shoestring") does not work from npm package

### ISSUE THREAD

**Issue by btakita** [filamentgroup/shoestring#93]
When I run:

`npm install shoestring`

Then:

`require("shoestring")`

I get:

`Error: Cannot find module 'shoestring' from '/project-dir'`

**Comment by zachleat** [comment]
Fixed with v1.0.4

**Comment by zachleat** [comment]
Well, we forgot a `main` entry in the package.json, so we’ve added a `v1.0.5` version with this.
